---
driver:
  name: digitalocean
  digitalocean_client_id: "<%= ENV['DIGITALOCEAN_CLIENT_ID']%>"
  digitalocean_api_key: "<%= ENV['DIGITALOCEAN_API_KEY']%>"
  driver_config:
    ssh_key_ids: "%<= ENV['DIGITALOCEAN_SSH_KEY_IDS']%>"

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver: digitalocean
    driver_config:
      image_id: 3448641
      region_id: 4

suites:
  - name: default
    run_list:
    attributes:
