---
driver:
  require_chef_omnibus: true
  name: ec2
  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID']%>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY']%>"
  aws_ssh_key_id: "<%= ENV['AWS_SSH_KEY_ID']%>"
  ssh_key: "<%= ENV['HOME']%>/ec2/<%= ENV['AWS_SSH_KEY_ID']%>.pem"

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver:
      image_id: ami-8997afe0
      username: root
      region: us-east-1
      availability_zone: us-east-1c

suites:
  - name: default
    run_list:
    attributes:
