---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver:
      provider: vmware_workstation
      box: learningchef/centos65
      box_url: learningchef/centos65
      synced_folders:
        - [".", "/vagrant"]

suites:
  - name: default
    run_list:
    attributes:
