---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: learningchef
    driver:
      box: learningchef/chefdk-box
      box_url: learningchef/chefdk-box
      synced_folders:
        - ["../..", "/learningchef"]

suites:
  - name: default
    run_list:
    attributes:
