---
driver:
  require_chef_omnibus: true
  name: rackspace
  rackspace_username: "<%= ENV['RACKSPACE_USERNAME']%>"
  rackspace_api_key: "<%= ENV['RACKSPACE_API_KEY']%>"
  public_key_path: "<%= ENV['RACKSPACE_PUBLIC_KEY_PATH']%>"

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver: rackspace
    driver_config:
      image_id: "592c879e-f37d-43e6-8b54-8c2d97cf04d4"
      flavor_id: "performance1-1"

suites:
  - name: default
    run_list:
    attributes:
