---
driver:
  name: gce
  google_project: "<%= ENV['GOOGLE_PROJECT']%>"
  google_client_email: "<%= ENV['GOOGLE_CLIENT_EMAIL']%>"
  google_key_location: "<%= ENV['GOOGLE_KEY_LOCATION']%>"

provisioner:
  name: chef_solo

platforms:
  - name: centos65
    driver: gce
    driver_config:
      area: us
      image_name: centos-6-v20140619

suites:
  - name: default
    run_list:
    attributes:
